import type { AddonGroup, MenuCategory, MenuItem } from "./types";

export const categories: MenuCategory[] = [
  { slug: "signatures", name: "Signatures", tagline: "The dishes we built our name on" },
  { slug: "rice-and-grains", name: "Rice & Grains", tagline: "Hand-stirred, smoky, never rushed" },
  { slug: "soups-and-swallow", name: "Soups & Swallow", tagline: "Heritage recipes, refined" },
  { slug: "grills-and-suya", name: "Grills & Suya", tagline: "Charcoal, patience, fire" },
  { slug: "small-chops", name: "Small Chops", tagline: "For sharing, for celebrating" },
  { slug: "sides", name: "Sides", tagline: "The supporting cast" },
  { slug: "drinks", name: "Drinks", tagline: "House-pressed and hand-mixed" },
  { slug: "desserts", name: "Desserts", tagline: "A graceful finish" },
];

const proteinGroup: AddonGroup = {
  id: "protein",
  label: "Choose your protein",
  kind: "single",
  required: true,
  options: [
    { id: "chicken", name: "Grilled chicken", priceDelta: 0 },
    { id: "beef", name: "Slow-braised beef", priceDelta: 800 },
    { id: "goat", name: "Asun goat", priceDelta: 1500 },
    { id: "fish", name: "Pan-seared tilapia", priceDelta: 1200 },
    { id: "prawns", name: "Tiger prawns", priceDelta: 2500 },
  ],
};

const spiceGroup: AddonGroup = {
  id: "spice",
  label: "Spice level",
  kind: "single",
  required: true,
  options: [
    { id: "mild", name: "Mild", priceDelta: 0 },
    { id: "medium", name: "Medium", priceDelta: 0 },
    { id: "hot", name: "Hot", priceDelta: 0 },
    { id: "fire", name: "Fire — chef's discretion", priceDelta: 0 },
  ],
};

const extrasGroup: AddonGroup = {
  id: "extras",
  label: "Add extras",
  kind: "multiple",
  required: false,
  max: 5,
  options: [
    { id: "plantain", name: "Sweet plantain (3 pcs)", priceDelta: 1000 },
    { id: "moi-moi", name: "Moi-moi", priceDelta: 1200 },
    { id: "extra-rice", name: "Extra rice", priceDelta: 1500 },
    { id: "egg", name: "Boiled egg", priceDelta: 500 },
    { id: "salad", name: "House salad", priceDelta: 1500 },
    { id: "sauce", name: "Extra pepper sauce", priceDelta: 600 },
  ],
};

const swallowGroup: AddonGroup = {
  id: "swallow",
  label: "Choose your swallow",
  kind: "single",
  required: true,
  options: [
    { id: "pounded-yam", name: "Pounded yam", priceDelta: 0 },
    { id: "amala", name: "Amala", priceDelta: 0 },
    { id: "eba", name: "Eba", priceDelta: 0 },
    { id: "semovita", name: "Semovita", priceDelta: 0 },
    { id: "wheat", name: "Wheat", priceDelta: 0 },
    { id: "fufu", name: "Fufu", priceDelta: 0 },
  ],
};

const sizeGroup: AddonGroup = {
  id: "size",
  label: "Portion size",
  kind: "single",
  required: true,
  options: [
    { id: "regular", name: "Regular", priceDelta: 0 },
    { id: "large", name: "Large", priceDelta: 1500 },
    { id: "share", name: "Sharing platter (2)", priceDelta: 4000 },
  ],
};

const skewerGroup: AddonGroup = {
  id: "skewers",
  label: "How many skewers?",
  kind: "single",
  required: true,
  options: [
    { id: "3", name: "3 skewers", priceDelta: 0 },
    { id: "5", name: "5 skewers", priceDelta: 2200 },
    { id: "10", name: "10 skewers", priceDelta: 5800 },
  ],
};

// Curated food photography from Unsplash. Reused thoughtfully across items.
const IMG = {
  jollof: "https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=900&q=80&auto=format&fit=crop",
  fried_rice: "https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=900&q=80&auto=format&fit=crop",
  ofada: "https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?w=900&q=80&auto=format&fit=crop",
  egusi: "https://images.unsplash.com/photo-1574484284002-952d92456975?w=900&q=80&auto=format&fit=crop",
  pepper_soup: "https://images.unsplash.com/photo-1547592180-85f173990554?w=900&q=80&auto=format&fit=crop",
  afang: "https://images.unsplash.com/photo-1546549032-9571cd6b27df?w=900&q=80&auto=format&fit=crop",
  banga: "https://images.unsplash.com/photo-1547592166-23ac45744acd?w=900&q=80&auto=format&fit=crop",
  pounded_yam: "https://images.unsplash.com/photo-1551782450-a2132b4ba21d?w=900&q=80&auto=format&fit=crop",
  suya: "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=900&q=80&auto=format&fit=crop",
  asun: "https://images.unsplash.com/photo-1544025162-d76694265947?w=900&q=80&auto=format&fit=crop",
  grilled_chicken: "https://images.unsplash.com/photo-1532550907401-a500c9a57435?w=900&q=80&auto=format&fit=crop",
  grilled_fish: "https://images.unsplash.com/photo-1535473895227-bdecb20fb157?w=900&q=80&auto=format&fit=crop",
  shawarma: "https://images.unsplash.com/photo-1561651823-34feb02250e4?w=900&q=80&auto=format&fit=crop",
  small_chops: "https://images.unsplash.com/photo-1606755962773-d324e0a13086?w=900&q=80&auto=format&fit=crop",
  puff_puff: "https://images.unsplash.com/photo-1551024601-bec78aea704b?w=900&q=80&auto=format&fit=crop",
  meat_pie: "https://images.unsplash.com/photo-1606491956689-2ea866880c84?w=900&q=80&auto=format&fit=crop",
  spring_roll: "https://images.unsplash.com/photo-1625938145744-533e82c2f60a?w=900&q=80&auto=format&fit=crop",
  plantain: "https://images.unsplash.com/photo-1604908554049-01b07d50ad34?w=900&q=80&auto=format&fit=crop",
  moi_moi: "https://images.unsplash.com/photo-1565958011703-44f9829ba187?w=900&q=80&auto=format&fit=crop",
  salad: "https://images.unsplash.com/photo-1551248429-40975aa4de74?w=900&q=80&auto=format&fit=crop",
  zobo: "https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=900&q=80&auto=format&fit=crop",
  chapman: "https://images.unsplash.com/photo-1551538827-9c037cb4f32a?w=900&q=80&auto=format&fit=crop",
  smoothie: "https://images.unsplash.com/photo-1505252585461-04db1eb84625?w=900&q=80&auto=format&fit=crop",
  palm_wine: "https://images.unsplash.com/photo-1559847844-5315695dadae?w=900&q=80&auto=format&fit=crop",
  cake: "https://images.unsplash.com/photo-1565958011703-44f9829ba187?w=900&q=80&auto=format&fit=crop",
  chin_chin: "https://images.unsplash.com/photo-1502741338009-cac2772e18bc?w=900&q=80&auto=format&fit=crop",
  ice_cream: "https://images.unsplash.com/photo-1501443762994-82bd5dace89a?w=900&q=80&auto=format&fit=crop",
};

export const items: MenuItem[] = [
  // Signatures
  {
    id: "i-platinum-jollof",
    slug: "platinum-jollof",
    name: "Platinum Jollof",
    description:
      "Our signature smoky party jollof, slow-cooked over open flame with hand-pounded peppers, finished with fried plantain and your choice of protein.",
    price: 7500,
    imageUrl: IMG.jollof,
    category: "signatures",
    tags: ["chef's-pick", "spicy"],
    prepMinutes: 25,
    available: true,
    addonGroups: [proteinGroup, spiceGroup, extrasGroup],
  },
  {
    id: "i-egusi-royale",
    slug: "egusi-royale",
    name: "Egusi Royale",
    description:
      "Hand-ground melon seed soup with smoked panla, assorted, and bitter leaf. Served with your choice of swallow.",
    price: 8800,
    imageUrl: IMG.egusi,
    category: "signatures",
    tags: ["chef's-pick"],
    prepMinutes: 30,
    available: true,
    addonGroups: [swallowGroup, spiceGroup],
  },
  {
    id: "i-suya-board",
    slug: "suya-board",
    name: "Suya Board",
    description:
      "Charcoal-grilled suya skewers with onions, tomato, fresh pepper, and our house yaji blend. Built to share.",
    price: 9500,
    imageUrl: IMG.suya,
    category: "signatures",
    tags: ["chef's-pick", "spicy"],
    prepMinutes: 18,
    available: true,
    addonGroups: [skewerGroup, spiceGroup],
  },
  {
    id: "i-asun-platter",
    slug: "asun-platter",
    name: "Asun Platter",
    description:
      "Smoky peppered goat, slow-roasted then tossed with scotch bonnet and onion. Best enjoyed with cold zobo.",
    price: 11000,
    imageUrl: IMG.asun,
    category: "signatures",
    tags: ["chef's-pick", "spicy"],
    prepMinutes: 25,
    available: true,
    addonGroups: [spiceGroup, sizeGroup],
  },

  // Rice & Grains
  {
    id: "i-jollof-classic",
    slug: "jollof-classic",
    name: "Classic Jollof Rice",
    description: "Long-grain rice, deep tomato base, smoky finish. A Sunday-lunch staple.",
    price: 5500,
    imageUrl: IMG.jollof,
    category: "rice-and-grains",
    prepMinutes: 20,
    available: true,
    addonGroups: [proteinGroup, spiceGroup, extrasGroup],
  },
  {
    id: "i-fried-rice",
    slug: "nigerian-fried-rice",
    name: "Nigerian Fried Rice",
    description: "Vegetable-laden fried rice with green peas, sweet corn, liver, and shrimp.",
    price: 6200,
    imageUrl: IMG.fried_rice,
    category: "rice-and-grains",
    prepMinutes: 22,
    available: true,
    addonGroups: [proteinGroup, extrasGroup],
  },
  {
    id: "i-ofada-rice",
    slug: "ofada-rice",
    name: "Ofada Rice & Ayamase",
    description: "Locally-sourced ofada rice with our slow-cooked green pepper ayamase stew.",
    price: 6800,
    imageUrl: IMG.ofada,
    category: "rice-and-grains",
    tags: ["spicy"],
    prepMinutes: 28,
    available: true,
    addonGroups: [proteinGroup, spiceGroup],
  },
  {
    id: "i-coconut-rice",
    slug: "coconut-rice",
    name: "Coconut Rice",
    description: "Fragrant rice simmered in fresh coconut milk with sweet pepper and bay.",
    price: 6500,
    imageUrl: IMG.fried_rice,
    category: "rice-and-grains",
    tags: ["new"],
    prepMinutes: 25,
    available: true,
    addonGroups: [proteinGroup, extrasGroup],
  },
  {
    id: "i-jollof-spaghetti",
    slug: "jollof-spaghetti",
    name: "Jollof Spaghetti",
    description: "Spaghetti tossed in our signature jollof base, finished with parmesan and basil.",
    price: 5800,
    imageUrl: IMG.jollof,
    category: "rice-and-grains",
    prepMinutes: 18,
    available: true,
    addonGroups: [proteinGroup, spiceGroup],
  },

  // Soups & Swallow
  {
    id: "i-egusi",
    slug: "egusi-soup",
    name: "Egusi Soup",
    description: "Melon seed soup with assorted meat, smoked fish, and bitter leaf.",
    price: 7800,
    imageUrl: IMG.egusi,
    category: "soups-and-swallow",
    prepMinutes: 30,
    available: true,
    addonGroups: [swallowGroup, spiceGroup],
  },
  {
    id: "i-afang",
    slug: "afang-soup",
    name: "Afang Soup",
    description: "Calabar afang leaf with waterleaf, periwinkle, and assorted meat.",
    price: 8500,
    imageUrl: IMG.afang,
    category: "soups-and-swallow",
    prepMinutes: 30,
    available: true,
    addonGroups: [swallowGroup],
  },
  {
    id: "i-banga",
    slug: "banga-soup",
    name: "Banga Soup",
    description: "Fresh palm fruit extract simmered with banga spice, scent leaf, and catfish.",
    price: 8200,
    imageUrl: IMG.banga,
    category: "soups-and-swallow",
    prepMinutes: 32,
    available: true,
    addonGroups: [swallowGroup, spiceGroup],
  },
  {
    id: "i-ogbono",
    slug: "ogbono-soup",
    name: "Ogbono Soup",
    description: "Wild mango seed draw soup with smoked fish and assorted meat.",
    price: 7600,
    imageUrl: IMG.afang,
    category: "soups-and-swallow",
    prepMinutes: 28,
    available: true,
    addonGroups: [swallowGroup],
  },
  {
    id: "i-pepper-soup",
    slug: "pepper-soup",
    name: "Goat Pepper Soup",
    description: "Aromatic broth with tender goat, scent leaf, and uziza. Soul-warming.",
    price: 7200,
    imageUrl: IMG.pepper_soup,
    category: "soups-and-swallow",
    tags: ["spicy"],
    prepMinutes: 25,
    available: true,
    addonGroups: [spiceGroup],
  },

  // Grills & Suya
  {
    id: "i-suya-skewers",
    slug: "beef-suya",
    name: "Beef Suya",
    description: "Charcoal-grilled beef skewers in yaji spice with sliced onion and fresh pepper.",
    price: 4500,
    imageUrl: IMG.suya,
    category: "grills-and-suya",
    tags: ["spicy"],
    prepMinutes: 15,
    available: true,
    addonGroups: [skewerGroup, spiceGroup],
  },
  {
    id: "i-grilled-chicken",
    slug: "grilled-chicken",
    name: "Grilled Chicken Quarter",
    description: "Marinated overnight in suya spice and herbs, grilled until smoky and juicy.",
    price: 5800,
    imageUrl: IMG.grilled_chicken,
    category: "grills-and-suya",
    prepMinutes: 22,
    available: true,
    addonGroups: [spiceGroup, extrasGroup],
  },
  {
    id: "i-grilled-tilapia",
    slug: "grilled-tilapia",
    name: "Grilled Tilapia",
    description: "Whole tilapia stuffed with herbs and lime, grilled over charcoal. Served with pepper sauce.",
    price: 9500,
    imageUrl: IMG.grilled_fish,
    category: "grills-and-suya",
    tags: ["chef's-pick"],
    prepMinutes: 28,
    available: true,
    addonGroups: [spiceGroup, extrasGroup],
  },
  {
    id: "i-shawarma",
    slug: "house-shawarma",
    name: "House Shawarma",
    description: "Suya-spiced chicken or beef in warm pita, garlic sauce, slaw, and our spicy red.",
    price: 4200,
    imageUrl: IMG.shawarma,
    category: "grills-and-suya",
    prepMinutes: 12,
    available: true,
    addonGroups: [proteinGroup, spiceGroup],
  },
  {
    id: "i-asun",
    slug: "asun",
    name: "Asun (Peppered Goat)",
    description: "Smoky goat, fresh pepper, and onion. The ultimate weekend treat.",
    price: 8500,
    imageUrl: IMG.asun,
    category: "grills-and-suya",
    tags: ["spicy"],
    prepMinutes: 22,
    available: false,
    addonGroups: [spiceGroup, sizeGroup],
  },

  // Small Chops
  {
    id: "i-small-chops-platter",
    slug: "small-chops-platter",
    name: "Small Chops Platter",
    description: "Puff-puff, samosa, spring roll, peppered gizzard, and chicken wings. Built to share.",
    price: 6500,
    imageUrl: IMG.small_chops,
    category: "small-chops",
    tags: ["chef's-pick"],
    prepMinutes: 18,
    available: true,
    addonGroups: [sizeGroup],
  },
  {
    id: "i-puff-puff",
    slug: "puff-puff",
    name: "Puff-Puff (12 pcs)",
    description: "Light, golden, lightly sweet. Best with our chocolate dip.",
    price: 3000,
    imageUrl: IMG.puff_puff,
    category: "small-chops",
    prepMinutes: 12,
    available: true,
  },
  {
    id: "i-meat-pie",
    slug: "meat-pie",
    name: "Meat Pie",
    description: "Flaky golden crust, seasoned beef, potato, and carrot.",
    price: 1500,
    imageUrl: IMG.meat_pie,
    category: "small-chops",
    prepMinutes: 8,
    available: true,
  },
  {
    id: "i-spring-rolls",
    slug: "spring-rolls",
    name: "Spring Rolls (6 pcs)",
    description: "Vegetable spring rolls with sweet chili dip.",
    price: 3200,
    imageUrl: IMG.spring_roll,
    category: "small-chops",
    tags: ["vegetarian"],
    prepMinutes: 10,
    available: true,
  },

  // Sides
  {
    id: "i-plantain",
    slug: "sweet-plantain",
    name: "Sweet Plantain (Dodo)",
    description: "Ripe plantain pan-fried until caramelised at the edges.",
    price: 2500,
    imageUrl: IMG.plantain,
    category: "sides",
    tags: ["vegan"],
    prepMinutes: 8,
    available: true,
  },
  {
    id: "i-moimoi",
    slug: "moi-moi",
    name: "Moi-Moi",
    description: "Steamed bean pudding with peppers, fish, and egg.",
    price: 2200,
    imageUrl: IMG.moi_moi,
    category: "sides",
    prepMinutes: 10,
    available: true,
  },
  {
    id: "i-salad",
    slug: "house-salad",
    name: "House Salad",
    description: "Crisp lettuce, cucumber, tomato, sweet corn, and our citrus dressing.",
    price: 3500,
    imageUrl: IMG.salad,
    category: "sides",
    tags: ["vegetarian"],
    prepMinutes: 6,
    available: true,
  },
  {
    id: "i-coleslaw",
    slug: "coleslaw",
    name: "Creamy Coleslaw",
    description: "Cabbage, carrot, sweet corn, and a hint of mustard.",
    price: 2200,
    imageUrl: IMG.salad,
    category: "sides",
    tags: ["vegetarian"],
    prepMinutes: 5,
    available: true,
  },

  // Drinks
  {
    id: "i-zobo",
    slug: "house-zobo",
    name: "House Zobo",
    description: "Hibiscus, ginger, pineapple, and a whisper of cloves. Served chilled.",
    price: 2200,
    imageUrl: IMG.zobo,
    category: "drinks",
    tags: ["vegan", "chef's-pick"],
    prepMinutes: 3,
    available: true,
  },
  {
    id: "i-chapman",
    slug: "chapman",
    name: "Classic Chapman",
    description: "Bitters, citrus, grenadine, cucumber. The Nigerian original.",
    price: 2500,
    imageUrl: IMG.chapman,
    category: "drinks",
    prepMinutes: 4,
    available: true,
  },
  {
    id: "i-smoothie",
    slug: "tropical-smoothie",
    name: "Tropical Smoothie",
    description: "Mango, pineapple, banana, and a hint of lime.",
    price: 2800,
    imageUrl: IMG.smoothie,
    category: "drinks",
    tags: ["vegan"],
    prepMinutes: 5,
    available: true,
  },
  {
    id: "i-palmwine",
    slug: "fresh-palm-wine",
    name: "Fresh Palm Wine",
    description: "Tapped at dawn, served chilled in a calabash.",
    price: 3500,
    imageUrl: IMG.palm_wine,
    category: "drinks",
    tags: ["new"],
    prepMinutes: 2,
    available: true,
  },
  {
    id: "i-water",
    slug: "still-water",
    name: "Still Water (75cl)",
    description: "Locally bottled.",
    price: 800,
    imageUrl: IMG.palm_wine,
    category: "drinks",
    prepMinutes: 1,
    available: true,
  },

  // Desserts
  {
    id: "i-chin-chin",
    slug: "chin-chin",
    name: "Chin Chin",
    description: "Crisp, lightly sweet, with a hint of nutmeg.",
    price: 2000,
    imageUrl: IMG.chin_chin,
    category: "desserts",
    tags: ["vegetarian"],
    prepMinutes: 3,
    available: true,
  },
  {
    id: "i-cake-slice",
    slug: "chocolate-cake",
    name: "Chocolate Cake Slice",
    description: "Dark chocolate ganache, four layers, mascarpone cream.",
    price: 3500,
    imageUrl: IMG.cake,
    category: "desserts",
    prepMinutes: 3,
    available: true,
  },
  {
    id: "i-icecream",
    slug: "ice-cream",
    name: "Ice Cream (2 scoops)",
    description: "Vanilla bean, strawberry, chocolate, or mango. Chef picks the pairing.",
    price: 2800,
    imageUrl: IMG.ice_cream,
    category: "desserts",
    tags: ["vegetarian"],
    prepMinutes: 2,
    available: true,
  },
];

export function getItemById(id: string): MenuItem | undefined {
  return items.find((i) => i.id === id);
}

export function getItemBySlug(slug: string): MenuItem | undefined {
  return items.find((i) => i.slug === slug);
}

export function getItemsByCategory(slug: MenuItem["category"]): MenuItem[] {
  return items.filter((i) => i.category === slug);
}
